/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be :

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.
*/
#include <iostream>
int problem2()
{
	long acc = 0, fib1 = 1, fib2 = 2, fibtmp = 0;
	while (fib2 < 4000000)
	{
		acc += !(fib2 % 2) ? fib2 : 0;
		fibtmp = fib1 + fib2;
		fib1 = fib2;
		fib2 = fibtmp;
	}
	return acc;
}