#pragma once
#include <vector>
int problem1();
int problem2();
int problem3();
int problem4();
int problem5();
int problem6();
int problem7();
int problem8();
int problem9();
int problem10();
int problem11();
int problem12();
int problem13();
int problem14();
int problem15();
int problem16();
int problem17();